app:
  build: .
  links:
   - redis
   - mock-server
  ports:
   - 5000:5000
  environment:
   - PORT_REDIS=6379
   - HOST_REDIS=redis
redis:
  image: redis
mock-server:
  image: alexaleluia12/mockserver
  ports:
   - "8080:8080"